import type { Metadata } from "next";
import { Inter, Roboto, Work_Sans } from "next/font/google";
import "./globals.scss";
import ClientSideToastContainer from "@/components/toastContainer";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  weight: ["500"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

const sans = Work_Sans({
  weight: ["300", "400"],
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${roboto.variable} ${sans.variable}`}>
        <div className="container">
          <ClientSideToastContainer />
          {children}
        </div>
      </body>
    </html>
  );
}
